version: "3.9"
services:
  rtmp:
    build: ./web/rtmp
    container_name: rtmp
    volumes:
      - ./data:/tmp/hls
  proxy:
    build: ./web/proxy
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    container_name: proxy
    volumes:
      - ./web/proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongo-data:
